# Generated by Django 5.2.14 on 2026-06-06 00:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('on_demand', 'On demand'), ('webhook', 'Webhook')], max_length=12)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('computed', models.JSONField(blank=True, default=dict)),
                ('fired', models.BooleanField(default=False)),
                ('log', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('_ciphertext', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('rule', 'Simple rule (threshold / % move)'), ('indicator', 'Technical indicator (RSI / MACD / MA)'), ('custom_python', 'Custom Python strategy')], max_length=16)),
                ('tickers', models.JSONField(default=list)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('code', models.TextField(blank=True)),
                ('schedule_kind', models.CharField(choices=[('manual', 'Manual only'), ('interval', 'Every N minutes (market hours)'), ('daily', 'Daily at a set time')], default='manual', max_length=12)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_at', models.CharField(blank=True, max_length=5)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'strategies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketDataSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('price', models.FloatField(blank=True, null=True)),
                ('pct_change', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='casabourse', max_length=40)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['ticker', '-fetched_at'], name='signalrunne_ticker_49eb0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('reason', models.JSONField(blank=True, default=dict)),
                ('price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='signalrunner.evaluation')),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='signalrunner.strategy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('telegram', 'Telegram')], default='telegram', max_length=12)),
                ('target', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='signalrunner.signal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='signalrunner.strategy'),
        ),
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy_name', models.CharField(blank=True, max_length=200)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('horizon_days', models.PositiveIntegerField(default=5)),
                ('take_profit_pct', models.FloatField(blank=True, null=True)),
                ('stop_loss_pct', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('log', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='signalrunner.strategy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('session_date', models.DateField()),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('return_pct', models.FloatField(blank=True, null=True)),
                ('won', models.BooleanField(null=True)),
                ('exit_kind', models.CharField(blank=True, max_length=12)),
                ('reason', models.JSONField(blank=True, default=dict)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='signalrunner.backtest')),
            ],
            options={
                'ordering': ['session_date'],
                'indexes': [models.Index(fields=['backtest', 'session_date'], name='signalrunne_backtes_5490fa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['ticker', '-created_at'], name='signalrunne_ticker_277be1_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['status', '-queued_at'], name='signalrunne_status_9624f8_idx'),
        ),
    ]
