# Generated by Django 5.2.14 on 2026-06-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalrunner', '0002_backtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('yield_score', models.FloatField(default=0)),
                ('value_score', models.FloatField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('momentum_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='EarningsExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('report_type', models.CharField(choices=[('annual', 'Annual'), ('semi_annual', 'Semi-annual'), ('other', 'Other')], default='annual', max_length=20)),
                ('fiscal_year', models.IntegerField()),
                ('period_end', models.DateField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('net_income', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('dividend_per_share', models.FloatField(blank=True, null=True)),
                ('total_assets', models.FloatField(blank=True, null=True)),
                ('equity', models.FloatField(blank=True, null=True)),
                ('revenue_growth_pct', models.FloatField(blank=True, null=True)),
                ('net_income_growth_pct', models.FloatField(blank=True, null=True)),
                ('eps_growth_pct', models.FloatField(blank=True, null=True)),
                ('ammc_url', models.URLField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('raw_text_snippet', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fiscal_year', '-period_end'],
                'unique_together': {('ticker', 'report_type', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='StockFundamentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('shares_outstanding', models.FloatField(blank=True, null=True)),
                ('week_52_high', models.FloatField(blank=True, null=True)),
                ('week_52_low', models.FloatField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('net_income', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('dividend_per_share', models.FloatField(blank=True, null=True)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('payout_ratio', models.FloatField(blank=True, null=True)),
                ('price_to_book', models.FloatField(blank=True, null=True)),
                ('pdf_source_url', models.URLField(blank=True)),
                ('data_quality', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('price_only', 'Price only')], default='partial', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['ticker', '-date'], name='signalrunne_ticker_9f4564_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
